minlp-tokenizer/README.md
=> add imprint in readme

minlp-tokenizer/setup.py
update python version requirement
=> update python version requirement

minlp-tokenizer/README.md
=> fix requirements in readme

minlp-tokenizer/setup.py
=> add python3.8 requirements

minlp-tokenizer/minlptokenizer/tokenizer.py, minlp-tokenizer/requirements.txt
目前这个版本，经过我的测试，在RTX TITAN下，能到150K左右，GPU利用能到50，只是波动比较大。如果能拆分CPU的计算部分，应该有希望提升到300-500K/S。
=> Add mutliprocess cut method in GPU

minlp-tokenizer/setup.py
=> upgrade version to 3.3.3

minlp-tokenizer/requirements.txt
=> fix requirements

minlp-tokenizer/minlptokenizer/tokenizer.py
fix blank bug in post-processing
=> fix blanck-bug in post processing

minlp-tokenizer/minlptokenizer/tokenizer.py, minlp-tokenizer/requirements.txt, minlp-tokenizer/setup.py
=> Hotfix postprocessing

minlp-tokenizer/minlptokenizer/tokenizer.py, minlp-tokenizer/setup.py
=> fix bug in full-width characters

duckling-fork-chinese/core/src/main/scala/duckling/dimension/episode/Rules.scala, duckling-fork-chinese/core/src/main/scala/duckling/dimension/quantity/Quantity.scala, duckling-fork-chinese/core/src/main/scala/duckling/dimension/season/Rules.scala, duckling-fork-chinese/core/src/main/scala/duckling/dimension/season/package.scala, duckling-fork-chinese/core/src/main/scala/duckling/dimension/time/Time.scala, duckling-fork-chinese/core/src/main/scala/duckling/ranking/Testing.scala, duckling-fork-chinese/core/src/test/scala/duckling/dimension/episode/EpisodeTest.scala, duckling-fork-chinese/core/src/test/scala/duckling/dimension/season/SeasonTest.scala, duckling-fork-chinese/core/src/test/scala/duckling/dimension/time/TimeDataTest.scala, duckling-fork-chinese/core/src/test/scala/duckling/dimension/time/TimeTest.scala
=> Season和Episode隐式表达增加Latent字段

duckling-fork-chinese/core/src/main/resources/reference.conf, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/EnumeratedDimension.java, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/FullDimensions.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/quantity/area/Area.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/quantity/area/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/quantity/area/Rules.scala, duckling-fork-chinese/server/src/main/resources/static/js/duckling-extract.js
=> [DUCK] 增加面积

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/quantity/area/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/quantity/area/Rules.scala
=> [DUCK] 面积扩充

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Time.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeDataTest.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeTest.scala
=> [DUCK] IMP完善simple信息，增加偏移字段

duckling-fork-chinese/README.md
=> IMP更新README

duckling-fork-chinese/core/src/main/resources/reference.conf, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/Api.scala
=> [DUCK] IMP 默认取消超时缓存

duckling-fork-chinese/server/src/main/scala/com/xiaomi/duckling/server/DucklingController.java
=> [DUCK]FIX增加xss过滤

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/FuzzyDayIntervals.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/LunarDays.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/task/NaiveBayesDebug.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/ApiTest.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/GeneralCaseTest.scala
1、支持“年三十”的表达  
2、修复"1分09秒"无法抽取的问题   
3、修复“明晚六点”，“昨晚六点”时间计算错误问题
=> IMP修复若干case

duckling-fork-chinese/core/src/main/resources/reference.conf, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/date/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Duration.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/predicates.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/ApiTest.scala, duckling-fork-chinese/server/src/main/scala/com/xiaomi/duckling/TokenVisualization.scala
=> [DUCK]FIX解决'上周一过去几天'抽取错误的问题

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/engine/LexiconLookup.scala, duckling-fork-chinese/project/Dependencies.scala
之前引入了依赖，但是仍然使用的HanLP中的实现，现在采用了HanLP的一个独立包
=> [DUCK] 替换AC自动机实现

duckling-fork-chinese/core/src/main/resources/reference.conf, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/Api.scala
=> [DUCK]IMP 移除超时缓存逻辑

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Time.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Types.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimeObjectHelpers.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimeValueHelpers.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/package.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/predicates.scala
1. 增加 时间点之前之后的表达
2. 填上了之前没有实现的`TimeOpenInterval`
=> [DUCK] 增加 "2000年以前" 的表达

duckling-fork-chinese/README.md
=> 更新duckling发布示例

duckling-fork-chinese/project/Dependencies.scala
=> [DUCK] fix vulnerability

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/project/Dependencies.scala
=> [DUCK] FIX After

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/date/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/date/LunarDates.scala
支持以下农历表达：  
(农|阴)历的?+date
date+的?(农|阴)历
=> [DUCK]IMP扩展农历表达

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/package.scala
=> 修复 11点15分到15点20分 回答的时间范围不正确的问题

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/fraction/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/fraction/Rules.scala
=> [DUCK]IMP抽取负百分比

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/FuzzyDayIntervals.scala
=> FIX解决'中午十点'时间错误问题

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/Resources.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/constellation/package.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/place/Types.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/SolarTermProvider.scala
=> [DUCK] 简化/加强资源加载

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/Times.scala
=> [DUCK]解决xx点[0|零]x分抽取错误问题

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala
=> [DUCK] 修复"未来几天"

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/date/Rules.scala
=> [DUCK] 支持上下半年

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Helpers.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/date/Examples.scala
调整12小时表达，如8点，当它与3号（日期）结合的时候，去掉既出8点又出20点的情况
Closes #115
=> [DUCK] 小时与更高grain结合的时候去掉扩展

duckling-fork-chinese/build.sbt, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/task/NaiveBayesConsole.scala, duckling-fork-chinese/project/Dependencies.scala
```
➜  duckling-fork-chinese git:(main) sbt core/console
[info] welcome to sbt 1.6.2 (...)
Welcome to Scala 2.11.12 (...).
Type in expressions for evaluation. Or try :help.
scala> com.xiaomi.duckling.task.NaiveBayesConsole.run()
```
```
duckling > 今天的天气
empty results
```
```
duckling > dimension time duration
```
```
duckling > 今天的天气
found 1 results
-1.38629 => {"timeValue": ...}}
this <cycle>["今天"]
-- regex["今"]
-- day (grain)["天"]
-- -- regex["天"]
```
=> [DUCK] 使用一些jline的completion功能，让debug起来更方便

duckling-fork-chinese/README.md, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/Types.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Time.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/task/NaiveBayesConsole.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeDataTest.scala
=> [DUCK] 增加选项，使得 duration+后 也能够与duration保持相同粒度

duckling-fork-chinese/build.sbt, duckling-fork-chinese/project/Dependencies.scala
包括 scala-2.13升级与commons-text更新
=> [DUCK] 修复CVE提示错误

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Types.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeDataTest.scala
=> [DUCK] 修复"三分钟后"，精度丢失的问题

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimeDataHelpers.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimeObjectHelpers.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimePredicateHelpers.scala
=> [DUCK] 支持"今天上午到明天八点"这类说法

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/date/Rules.scala
=> [DUCK] 增加今天明天的支持

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Time.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/SolarTerms.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/ranking/Testing.scala
=> [DUCK]支持春夏秋冬四季表达

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/predicates.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/FuzzyDayIntervals.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/Times.scala
=> [DUCK]解析零点

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/Resources.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/ranking/Bayes.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/ranking/KryoSerde.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/ranking/NaiveBayesLearning.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/ranking/NaiveBayesRank.scala, duckling-fork-chinese/project/Dependencies.scala
* 没错，之前的适配算是失败了。安卓请使用1.3.2开始的lite版本
=> [DUCK] 再次面向安卓适配，重做了kryo序列化，移除了chill

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/FuzzyDayIntervals.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala
=> 支持：三月五号的九天后

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/grain/Rules.scala
=> [DUCK] 增加一个点/一个钟的说法

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Types.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/enums/Hint.java, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimeDataHelpers.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimeObjectHelpers.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/package.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/Dates.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/SolarTerms.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeTest.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/NaiveBayesConsole.scala
=> [DUCK] 修复一种时间区间的问题，"十一点半到明天早上八点"，起始时间不正确

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/JsonSerde.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/repeat/Repeat.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/repeat/Rules.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimeValueHelpers.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/repeat/Examples.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/NaiveBayesDebug.scala
=> [DUCK] 增加"隔三天"说法

duckling-fork-chinese/core/src/main/resources/reference.conf, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Time.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Rules.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/NaiveBayesConsole.scala
- 将fuzzy/sequence参数移入了options中，比在reference.conf中配置灵活一些
- x.y 小时 扩展到 x.y 年/月/分钟
=> [DUCK] 小数时间粒度功能拓展

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/package.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala
=> [DUCK] Time: 支持9-9点

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/Times.scala
=> [DUCK] 修正is12H的传递

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/FuzzyDayIntervals.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/Times.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeTest.scala
=> [DUCK] 强化修复 #185

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Rules.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/grain/TimeGrainTest.scala
=> [DUCK] 修复不合理的duration组合

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/FuzzyDayIntervals.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/NaiveBayesDebug.scala
=> [DUCK] 为 上午/下午... 默认开启beforeEndOfInterval

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/ApiTest.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala
=> imp: 最近一周输出范围由本周改为最近7天

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala
=> imp:支持后面/将来十天

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/package.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeDataTest.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/NaiveBayesConsole.scala
比如：现在是上午，解析使用过去模式，上午将会是昨天的上午，应该出今天的上午
=> [DUCK] 修复当前时间段满足条件的不在过去中的问题

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/FormTest.scala
=> [DUCK] 强化 Form，只在确定的情况下增加

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Time.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimePredicateHelpers.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/package.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TypesTest.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/NaiveBayesDebug.scala
- 当前是12号14点
- 12号下午 
目前是给出下个月的12号下午，在 `beforeEndOfInterval` 有效的情况下，应该给出本月12号的。
=> [DUCK] 修复区间未结束时的区间判断不正确的问题
