.apollo.yml, .gitlab-ci.yml, duckling-fork-chinese/README.md, duckling-fork-chinese/bin/package, duckling-fork-chinese/bin/stop, duckling-fork-chinese/build.sbt, duckling-fork-chinese/project/plugins.sbt
进行了大幅简化，自动版本号之类的功能没做，需要手动打TAG。
验证了内外部库可以统一走来，发布是可以统一的。引入了小米内部部署需要的配置文件。
=> [DUCK] SonaType发布

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/constellation/Rules.scala
在精简依赖的过程中检测到lazy加载未正确生效的问题，星座会加载星座资源。
=> [DUCK] Fix lazy loading

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/seq/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/seq/package.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Examples.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/package.scala
Closes #111 
错误修复
1. 一小时零五分，零五 在leadingZero的判断中被滤掉，恢复，**需要看看之前是考虑的什么情况**
2. 一小时五分，五分是一个latent表达，这里允许生成latent，并在之前使用Duration的地方都加上了不为latent的条件，使得条件的整体使用范围并不会扩大。
@zhangsonglei 方便地话，做一个前后对比是比较好的。
=> [DUCK] 修复 一小时零九分 和 1小时9分

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/Types.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/Numeral.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Time.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/ranking/Testing.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/numeral/NumeralTest.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/package.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeDataTest.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeTest.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/ranking/AnswersSelection.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/AnswerSizeDetector.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/NaiveBayesConsole.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/NaiveBayesDebug.scala, duckling-fork-chinese/server/src/main/scala/com/xiaomi/duckling/server/DucklingController.java
- ！这是为了后续兼容性考虑的非兼容修改
- 子选项使用java bean来承载，这样就能做到向前/后兼容了，避开了在增加参数后，由于使用全参构造函数带来的参数个数不匹配的问题
- 好处：在升级duckling后，旧代码不会再因为引入的新参数未设置而报错（全参构造函数变了）
=> [DUCK] 子选项参数使用无参Java Bean重做，提升兼容性

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/package.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TimeDataTest.scala
- 当前4:30，问4点，应该给16:00而不是4:00
-  当前12号，问12号，应该还是12号，而不是下个月12号
- 当前1月，问1月，应该还是本月
=> [DUCK] 当前4:30，问4点，应该给16:00而不是4:00

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/predicates.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/FuzzyDayIntervals.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala
新增说法支持
- 3到5号
- 八到九点
- 明天上午八到九点
增加不合理表达的支持（只在与小时求交时生效），比如
- 中午11点
- 早上3点
- 上午5点
=> [DUCK] 新增说法支持明天上午8到9点，支持中午11点等

duckling-fork-chinese/core/src/main/resources/reference.conf, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/EnumeratedDimension.java, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/FullDimensions.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/act/Act.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/act/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/act/package.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/act/ActTest.scala, duckling-fork-chinese/doc/支持的Dimension.md, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/act/Examples.scala, duckling-fork-chinese/server/src/main/resources/static/js/duckling-extract.js
=> [DUCK]新增act dim

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/fraction/Fraction.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/fraction/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/fraction/package.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/numeral/fraction/Examples.scala
70%=FractionData(0.7000000000000001,70.0,100.0)
=> [DUCK] 解决浮点数精度问题

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/date/LunarDates.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/numeral/Examples.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/date/Examples.scala
case1："三月十八农历"提醒我xxx【农历的三月十八】；"三月十八农历"是几月几号【三月十八对应的农历日期】  
case2：负一百点三，预期：-100.3，实际：-99.7
=> FIX取消有歧义的农历表达，解决小数负值表达value错误问题

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala
修改【duration+内】interval范围等同【未来+duration】。eg，token=三天内：    
当前时间：2023-10-18T11:21:15
原始结果：[2023-10-18T11:21:15, 2023-10-21T11:21:15]
现在结果：[2023-10-18T00:00:00, 2023-10-21T00:00:00]
=> IMP修改【duration+内】interval范围等同【未来+duration】

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/quantity/Quantity.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/quantity/distance/Rules.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/ApiTest.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/quantity/QuantityTest.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/temperature/TemperatureTest.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/quantity/distance/Examples.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala
=> feat: 扩充距离表达方式

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/date/Rules.scala
最近，只会输出未来三天  
当设recentInFuture或alwaysInFuture为false时，改为过去三天
=> fix: 最近，根据timeoption自定义是未来时间还是过去时间

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/date/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/repeat/Rules.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/repeat/RepeatValueTest.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/date/Examples.scala
=> [DUCK] 时间支持更多说法

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/ordinal/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/ordinal/Examples.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala
支持time+ordinal+grain：今年第一天，今年最后一天，本月倒数第三天  
https://github.com/XiaoMi/MiNLP/issues/226
=> [DUCK]feat:支持time+ordinal+grain

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/Types.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Types.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/HolidayProvider.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/package.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimeValueHelpers.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/repeat/Examples.scala
- 增加少量节日说法
- 支持除夕晚上8点，扩展了Sequence的表达
=> [DUCK] 节日更新 & 序列时间重做，扩展适用范围

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/repeat/Rules.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/repeat/Examples.scala
- repeat **每个上午3号下午三点半** 能组合出来的问题
- time intersect过程中form丢失的问题（明天的上午），上午的PartOfDay信息丢失
=> [DUCK] 修复repeat/time 两个问题

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/numeral/Predicates.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/rule/Times.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala
- 05分 latent = false
- 50分 latent = true
Close #244
=> [DUCK] 支持x分

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Rules.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/package.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/grain/Rules.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/duration/DurationTest.scala
=> [DUCK] 持续时间表达收缩

duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Rules.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/duration/Examples.scala
=> [DUCK] duration: 增加 一点五二小时 类的支持

.github/workflows/duckling.yml, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/Time.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/helper/TimePredicateHelpers.scala, duckling-fork-chinese/core/src/main/scala/com/xiaomi/duckling/dimension/time/package.scala, duckling-fork-chinese/core/src/test/scala/com/xiaomi/duckling/dimension/time/TypesTest.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/dimension/time/Examples.scala, duckling-fork-chinese/learning/src/main/scala/com/xiaomi/duckling/task/NaiveBayesDebug.scala
- 回退 #248，实现不太好
- 仿照 PartOfDay 中 beforeEndOfInterval的方式重做
效果：12号下午，问12号下午，给出的是12号下午
=> [DUCK] PartOfDay未结束区间参考重做
